name: document_selfie_verification
description: This widget provides a comprehensive solution for capturing and verifying both documents and selfies within a Flutter application. It seamlessly integrates camera access, image processing, and validation features to ensure a smooth user experience.
version: 0.0.32
homepage: https://github.com/tyba-co/document_selfie_verification

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  camera: ^0.10.5+9
  convert_native_img_stream: ^0.0.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  google_ml_kit: ^0.16.2
  image: ^4.1.6
  js: ^0.6.7
  logger: ^2.0.2+1
  path_provider: ^2.1.1
  system_info_plus: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/